/* This interface will be used to separate the different parts of the phrase out */
export interface Phrase {
  id: number;
  object: string;
  particle: string;
  kanji: string;
  hiragana: string;
  imageURL: string;
  audioURL: string;
}

// You should be able to construct a "Phrase" as long as you include each part
// Invariant: a pair of transitive/intransitive verbs always comes next to each other
export const phraseList: Phrase[] = [
  {
    id: 0,
    object: "ドア",
    particle: "を",
    kanji: "閉める",
    hiragana: "しめる",
    imageURL: "images/door_close_t.png",
    audioURL: "audio/door_close_t.mp3",
  },
  {
    id: 1,
    object: "ドア",
    particle: "が",
    kanji: "閉まる",
    hiragana: "しまる",
    imageURL: "images/door_close_i.png",
    audioURL: "audio/door_close_i.mp3",
  },
  {
    id: 2,
    object: "ドア",
    particle: "を",
    kanji: "開ける",
    hiragana: "あける",
    imageURL: "images/door_open_t.png",
    audioURL: "audio/door_open_t.mp3",
  },
  {
    id: 3,
    object: "ドア",
    particle: "が",
    kanji: "開く",
    hiragana: "あく",
    imageURL: "images/door_open_i.png",
    audioURL: "audio/door_open_i.mp3",
  },
  {
    id: 4,
    object: "電気",
    particle: "を",
    kanji: "つける",
    hiragana: "つける",
    imageURL: "images/light_on_t.png",
    audioURL: "audio/light_on_t.mp3",
  },
  {
    id: 5,
    object: "電気",
    particle: "が",
    kanji: "つく",
    hiragana: "つく",
    imageURL: "images/light_on_i.png",
    audioURL: "audio/light_on_i.mp3",
  },
  {
    id: 6,
    object: "電気",
    particle: "を",
    kanji: "消す",
    hiragana: "けす",
    imageURL: "images/light_off_t.png",
    audioURL: "audio/light_off_t.mp3",
  },
  {
    id: 7,
    object: "電気",
    particle: "が",
    kanji: "消える",
    hiragana: "きえる",
    imageURL: "images/light_off_i.png",
    audioURL: "audio/light_off_i.mp3",
  },
  {
    id: 8,
    object: "シャツ",
    particle: "を",
    kanji: "汚す",
    hiragana: "よごす",
    imageURL: "images/shirt_dirty_t.png",
    audioURL: "audio/shirt_dirty_t.mp3",
  },
  {
    id: 9,
    object: "シャツ",
    particle: "が",
    kanji: "汚れる",
    hiragana: "よごれる",
    imageURL: "images/shirt_dirty_i.png",
    audioURL: "audio/shirt_dirty_i.mp3",
  },
  {
    id: 10,
    object: "おもちゃ",
    particle: "を",
    kanji: "こわす",
    hiragana: "こわす",
    imageURL: "images/toy_break_t.png",
    audioURL: "audio/toy_break_t.mp3",
  },
  {
    id: 11,
    object: "おもちゃ",
    particle: "が",
    kanji: "こわれる",
    hiragana: "こわれる",
    imageURL: "images/toy_break_i.png",
    audioURL: "audio/toy_break_i.mp3",
  },
  {
    id: 12,
    object: "いぬ",
    particle: "を",
    kanji: "入れる",
    hiragana: "いれる",
    imageURL: "images/dog_enter_t.png",
    audioURL: "audio/dog_enter_t.mp3",
  },
  {
    id: 13,
    object: "いぬ",
    particle: "が",
    kanji: "入る",
    hiragana: "はいる",
    imageURL: "images/dog_enter_i.png",
    audioURL: "audio/dog_enter_i.mp3",
  },
  {
    id: 14,
    object: "ねこ",
    particle: "を",
    kanji: "出す",
    hiragana: "だす",
    imageURL: "images/cat_leave_t.png",
    audioURL: "audio/cat_leave_t.mp3",
  },
  {
    id: 15,
    object: "ねこ",
    particle: "が",
    kanji: "出る",
    hiragana: "でる",
    imageURL: "images/cat_leave_i.png",
    audioURL: "audio/cat_leave_i.mp3",
  },
  {
    id: 16,
    object: "ペン",
    particle: "を",
    kanji: "おとす",
    hiragana: "おとす",
    imageURL: "images/pen_fall_t.png",
    audioURL: "audio/pen_fall_t.mp3",
  },
  {
    id: 17,
    object: "ペン",
    particle: "が",
    kanji: "おちる",
    hiragana: "おちる",
    imageURL: "images/pen_fall_i.png",
    audioURL: "audio/pen_fall_i.mp3",
  },
  {
    id: 18,
    object: "おゆ",
    particle: "を",
    kanji: "わかす",
    hiragana: "わかす",
    imageURL: "images/water_boil_t.png",
    audioURL: "audio/water_boil_t.mp3",
  },
  {
    id: 19,
    object: "おゆ",
    particle: "が",
    kanji: "わく",
    hiragana: "わく",
    imageURL: "images/water_boil_i.png",
    audioURL: "audio/water_boil_i.mp3",
  },
];
